# Generated by Django 4.0.4 on 2022-06-23 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.IntegerField(max_length=100)),
                ('telefone', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=100)),
                ('rua', models.CharField(max_length=100)),
                ('bairro', models.DateField(max_length=8)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.IntegerField(max_length=100)),
            ],
        ),
    ]
